services:
  app:
    build: .
    container_name: retkikohteet-app
    ports:
      - "8001:80"
    depends_on:
      - db
    environment:
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    volumes:
      - ./:/var/www/html

  db:
    image: mariadb:11
    container_name: retkikohteet-db
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    volumes:
      - retkikohteet_db_data:/var/lib/mysql

volumes:
  retkikohteet_db_data: